### ISSUE TITLE
更新最新版本后【0.7.1】，使用cookie没有返回任何东西，一直在请求中。。。。。。最后报错：'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by xiaolvtongxue-zt** [acheong08/EdgeGPT#467]

**Comment by MonsterDruide1** [comment]
Might be fixed by #466 , that message is something I also observed when dealing with the error.

**Comment by xiaolvtongxue-zt** [comment]
> Might be fixed by #466 , that message is something I also observed when dealing with the error.

Thank you very much, the problem has been solved.
The problem was solved by wrapping it in list. #466 

[https://github.com/acheong08/EdgeGPT/pull/466/commits/213e18a439020eea776b7c48bf6945790c4dabad](url)

Replace "locationHints": get_location_hint_from_locale(locale).
Modify to read:
"locationHints": [get_location_hint_from_locale(locale)].

**Comment by acheong08** [comment]
That doesn't fix the full issue. I added the fix. Sorry about that
